Repository ciaolavoro/ciao-lavoro, pull requests merged in 2024-02, with the labels that each got.

#29 Tarea #22 - Workflow de CI completado
  .github/workflows/codacy-ci.yml
Labels: enhancement

#31 Fix #22 - Arreglo del Workflow (cobertura y acceso a directorios)
  .github/workflows/codacy-ci.yml
Labels: bug

#32 Fix #22 - 2º Intento de arreglo del Workflow (coverage añadido a requirements.txt)
  .github/workflows/codacy-ci.yml
  backend/requirements.txt
Labels: bug

#33 Fix #22 - Tercer intento de arreglo de Workflow (cambio de archivo generado, xml por html)
  .github/workflows/codacy-ci.yml
Labels: bug

#62 Task 1.6 - Modelo de servicio/42 DONE
  README.md
  backend/api/serializers.py
  backend/api/views.py
  backend/ciao_lavoro/settings.py
  backend/ciao_lavoro/urls.py
  backend/db.sqlite3
  backend/requirements.txt
  backend/service/__init__.py
  backend/service/admin.py
  backend/service/apps.py
  backend/service/migrations/0001_initial.py
  backend/service/migrations/__init__.py
  backend/service/models.py
  backend/service/serializers.py
  backend/service/tests.py
  backend/service/urls.py
  backend/service/views.py
  info.yml
Labels: backend, desarrollo

#64 Task 1.11 - Vista Detallada de Servicio/47 DONE
  frontend/src/assets/service/talonflame.jpg
  frontend/src/components/service/Service.jsx
  frontend/src/main.jsx
Labels: frontend, desarrollo
