Repository ciaolavoro/ciao-lavoro, pull requests merged in 2024-05, with the labels that each got.

#520 Fix-P.8-Reviews/512 FIXED
  frontend/src/components/service/Review.jsx
Labels: fix, frontend

#522 Fix P.3 - Boton de review/503 DONE
  backend/service/urls.py
  backend/service/views.py
  frontend/src/api/Service.api.js
  frontend/src/components/service/Service.jsx
Labels: fix, backend, frontend

#523 Fix p.4 usuarios /508 FIXED
  frontend/src/components/register/Register.jsx
  frontend/src/utils/validation.js
Labels: fix, frontend

#526 Fix 9 - Interfaz #513
  frontend/src/components/Navbar.jsx
Labels: fix, frontend

#524 Fix 6 - Trabajos #510
  frontend/src/components/service/CreateJob.jsx
Labels: fix, frontend

#525 Fix 7 contratos/511 DONE
  frontend/src/components/contract/ContractCardWorker.jsx
  frontend/src/components/contract/CreateContract.jsx
  frontend/src/utils/validation.js
Labels: fix, frontend

#532 Doc pilots/530
  docs/PPL/Docs Obligatorios/PilotUsersReports/pilots.md
Labels: documentación

#527 Fix P.5 - servicios/509 DONE
  frontend/src/components/home/Home.jsx
  frontend/src/components/service/Service.jsx
Labels: fix, hotfix

#535 Doc -Pilot User Commitment Agreement /533 DONE
  docs/PPL/Docs Obligatorios/pilotUsersCommitmentAgreements/CA_CiaoLavoro&Shard3D.pdf
Labels: documentación

#538 Doc - report.md /529 DONE
  docs/PPL/Docs Obligatorios/report.md
Labels: documentación

#537 Doc - Anuncio para las pantallas de la ETSII /517 DONE
  docs/PPL/Docs Adionales/AnuncioETSII/CiaoLavoro_G6.pptx
  docs/PPL/Docs Adionales/AnuncioETSII/CiaoLavoro_G6_Imagen1.jpg
  docs/PPL/Docs Adionales/AnuncioETSII/CiaoLavoro_G6_Imagen2.jpg
Labels: documentación

#548 Doc - ai usage report/490 DONE
  docs/PPL/Docs Obligatorios/AI-usage.md
Labels: documentación

#549 DOCS que faltaban
  docs/PPL/Docs Obligatorios/PilotUsersPerformanceEvaluation.md
  docs/PPL/Docs Obligatorios/revision.md
Labels: documentación

#566 Contribución KB /556: DONE
  docs/WPL/report.md
Labels: documentación

#571 Doc pilot User CA CiaoLavoro + SHAR3D v1.5/570 DONE
  docs/WPL/Docs Obligatorios/Pilot User CA/CA_CiaoLavoro&SHAR3D.pdf
  docs/WPL/Docs Obligatorios/report.md
Labels: documentación

#586 Doc - Firmar Commitment Agreement v1.9/557 DONE
  docs/WPL/CommitmentAgreement_v1.9/AC_adrgarcha_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_alisanhos_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_alvhidrod_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_antbarjim1_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_diegonqui_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_fracamcam_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_javgrogom_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_joaarrdia_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_joscobari_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_pabcueper_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_pabmatang_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/AC_samalbort_v1.9.md
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaAdrián.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaAlex.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaAntonio.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaDiego.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaFran.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaJavi.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaJoaquín.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaJoseLuis.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaJoséLuis.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaPabloCuenca.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaPabloMateos.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaSamu.png
  docs/WPL/CommitmentAgreement_v1.9/ImágenesFirma/firmaÁlvaro.png
  docs/WPL/commitmentAgreement.md
Labels: documentación

#585 Doc - Information provided by pilot users/568 DONE
  docs/WPL/Docs Obligatorios/PilotUsersReports/InformationProvidedByPilotUsers.md
  docs/WPL/Docs Obligatorios/PilotUsersReports/img-mejora.png
  docs/WPL/Docs Obligatorios/PilotUsersReports/img-satisfaccion.png
  docs/WPL/Docs Obligatorios/PilotUsersReports/img-util.png
Labels: documentación

#592 Doc pilotusersperformanceevaluation/583 DONE
  docs/WPL/Docs Obligatorios/PilotUsersPerformanceEvaluation.md
Labels: documentación

#593 Fix 2 - Contratos /589 FIXED
  frontend/src/components/contract/CreateContract.jsx
Labels: fix, frontend

#594 Fix 5.1 - servicios/588 DONE
  frontend/src/components/service/CreateJob.jsx
  frontend/src/components/service/Service.jsx
Labels: fix, frontend

#590 Doc - Pilots.md/577
  docs/WPL/Docs Obligatorios/pilots.md
Labels: documentación

#595 Doc revision.md/584 DONE
  docs/WPL/Docs Obligatorios/revision.md
Labels: documentación

#598 Doc - Time Effort Report #579 DONE
  docs/WPL/TimeEffortReportGlobal/Adrian.pdf
  docs/WPL/TimeEffortReportGlobal/Alexander.pdf
  docs/WPL/TimeEffortReportGlobal/Antonio.pdf
  docs/WPL/TimeEffortReportGlobal/Diego.pdf
  docs/WPL/TimeEffortReportGlobal/Francisco.pdf
  docs/WPL/TimeEffortReportGlobal/Grupal.pdf
  docs/WPL/TimeEffortReportGlobal/Javier.pdf
  docs/WPL/TimeEffortReportGlobal/Joaquin.pdf
  docs/WPL/TimeEffortReportGlobal/Jose Luis.pdf
  docs/WPL/TimeEffortReportGlobal/Pablo Cuenca.pdf
  docs/WPL/TimeEffortReportGlobal/Pablo Mateo.pdf
  docs/WPL/TimeEffortReportGlobal/Samuel.pdf
  docs/WPL/TimeEffortReportGlobal/Álvaro.pdf
  docs/WPL/TimeEffortReportWPL/Adrian.pdf
  docs/WPL/TimeEffortReportWPL/Alexander.pdf
  docs/WPL/TimeEffortReportWPL/Antonio.pdf
  docs/WPL/TimeEffortReportWPL/Diego.pdf
  docs/WPL/TimeEffortReportWPL/Francisco.pdf
  docs/WPL/TimeEffortReportWPL/General.pdf
  docs/WPL/TimeEffortReportWPL/Javier.pdf
  docs/WPL/TimeEffortReportWPL/Joaquin.pdf
  docs/WPL/TimeEffortReportWPL/Jose Luis.pdf
  docs/WPL/TimeEffortReportWPL/Pablo Cuenca.pdf
  docs/WPL/TimeEffortReportWPL/Pablo Mateos.pdf
  docs/WPL/TimeEffortReportWPL/Samuel.pdf
  docs/WPL/TimeEffortReportWPL/Álvaro.pdf
Labels: documentación
